name: 'Submodules Sync'
on:
  repository_dispatch: # 서브모듈 트리거
  workflow_dispatch:  # 수동실행

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    env:
      GIT_AUTHOR_NAME: github-actions
      GIT_AUTHOR_EMAIL: github-actions@github.com
      GIT_COMMITTER_NAME: github-actions
      GIT_COMMITTER_EMAIL: github-actions@github.com

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.TOKEN}}
          submodules: recursive

      - name: Update submodule to latest
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule update --remote --recursive
          ls -la _posts || true
          git add .
          git commit -m "chore: update submodules to latest" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin master